### ISSUE TITLE
conf.d script overwrites local modifications

### ISSUE THREAD

**Issue by charego** [tomyun/base16-fish#3]
It would be nice to choose a theme with a `base16-<chosentheme>` function, then tweak a few colors. In my case I want to run:

```
> base16-snazzy
> set -U fish_color_autosuggestion a5a5a9
> set -U fish_color_comment a5a5a9
> set -U fish_color_param white
```

However with `conf.d/base16.fish` whenever I open a new shell, this plugin resets all the colors. I would expect the plugin to set the universal variables once when you call `base16-<chosentheme>`, not every time you open a new shell.

Thoughts? And thank you for the plugin!

**Comment by tomyun** [comment]
Sorry for the slow response. Somehow I didn't get any notification from my own repo.

I remember this plugin was initially coded to set colors through universal variables. Then it didn't feel alright since there was no simple way to clean them up when the plugin was uninstalled.

But your case sounds very reasonable and I believe there should be a way to handle this more nicely, i.e., making use of event system in [Fisher](https://github.com/jorgebucaran/fisher).

**Comment by charego** [comment]
Since creating this issue fish introduced the `theme` subcommand to `fish_config`. It doesn't solve all the problems (you can still get stale variables after changing themes), but I'm closing this.
